matrix:
  include:
    - os: osx
      osx_image: xcode11
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      language: node_js
      node_js: "12"
      sudo: required
      dist: bionic
      services:
        - xvfb
      deploy:
        provider: snap
        channel: edge
        skip_cleanup: true
      addons:
        apt:
          packages:
            - rpm

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3 # give xvfb some time to start
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo snap refresh && sudo snap install snapcraft --classic &&echo $SNAP_TOKEN | snapcraft login --with -

before_install:
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "[skip travis] has been found, exiting" && exit 0 ; else echo "[skip travis] has not been found, continuing" ; fi
  - npm install -g yarn

script:
  - npm run pre-test
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      xvfb-run --server-args="-screen 0 1024x768x24"npm run test
    else
      npm run test
    fi
  - |
    if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip build]" ; then
      echo "[skip build] has been found, exiting" && exit 0 ;
    elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run build-linux
    else
      npm run output -m
    fi

branches:
  - release
  - test