# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ build, test ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    environment: build
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip win]')"

    strategy:
      matrix:
        os: [windows-2022]
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # before_install:
    - run: npm install --global --production windows-build-tools
    - run: npm install -g yarn
    - run: npm install -g node-gyp
    - run: npm i

    # script:
    - run: npm run pre-test

    - name: build
      if: "!contains(github.event.head_commit.message, 'skip build')"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_NUMBER: ${{ secrets.BUILD_NUMBER }}
      run: npm run build-win

