# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: win

on:
  push:
    branches: [ build, test ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    environment: build
    if: "!contains(github.event.head_commit.message, '[skip build]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip win]')"

    strategy:
      matrix:
        os: [windows-2022]
        node-version: [ 16.x ]
        python-version: ['3.7']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/setup-python@v3
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: npm install -g node-gyp

    # before_install:
    # - run: npm install --global --production windows-build-tools --vs2015
    - run: npm install -g yarn
    - run: npm un -S node-bash
    - run: npm i

    # script:
    - run: npm run pre-test

    - name: build
      if: "!contains(github.event.head_commit.message, 'skip build')"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_NUMBER: ${{ secrets.BUILD_NUMBER }}
      run: npm run build-win

