# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: win7-tar

on:
  push:
    branches: [ build, test, build-only ]

jobs:
  build:

    runs-on: windows-2022
    environment: build
    if: "!contains(github.event.head_commit.message, '[skip build]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip win]') && !contains(github.event.head_commit.message, '[skip win7-tar]')"

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x

    - uses: actions/setup-python@v5
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: npm install -g node-gyp

    # before_install:
    # - run: npm install --global --production windows-build-tools --vs2015
    - run: npm install -g yarn
    - run: npm un vite node-pty serialport electron
    - run: npm i
    - run: npm i -D electron@22.3.27
    - run: npm i -S -E node-pty@1.1.0-beta14
    - run: npm i -S -E serialport@13.0.0
    - run: npm i -D vite@4

    # script:
    - run: npm run b

    - name: build
      if: "!contains(github.event.head_commit.message, 'skip build')"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_NUMBER: ${{ secrets.BUILD_NUMBER }}
      run: node build/bin/build-win7-tar

