name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    environment: build
    steps:
      - uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: electerm.electerm
          installer-regex: '.*.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
